log: './log'
telegram:
  workers: 3
  proxy:
    server: 'your.proxy.com'
    port: 3871
    user: 'user'
    password: 'password'
  api: 'https://api.telegram.org/bot'
  token: 'your bot token'
  admin: [hear admin ids per comma]
  time: 
    update: 3
    skip_messages: 60
imgur:
  clientID: 'your id'
  secret: 'and secret'
reddit:
  clientID: 'id again'
  secret: 'and secret'
  username: 'user'
  password: 'password'
  limit: 50
  categories:
    - name: 'NSFW'
      source: ['/r/NSFW_GIF/hot','/r/AmateurAsianGirls/hot']
    - name: 'Celebrities' 
      source: ['/r/celebrities/hot']
    - name: 'RealGirls'
      source: ['/r/RealGirls/hot']